### PR TITLE
Classify Yelp reviews using NLP

### PR DESCRIPTION
**Pull request by yamini**

### CODE REVIEW

**Comment by drew** [comment]
This looks really similar to the existing `classify_freetext_with_nlp.ipynb` notebook. What's the motivation for the new dataset and notebook?

**Comment by yamini** [comment]
> This looks really similar to the existing `classify_freetext_with_nlp.ipynb` notebook. What's the motivation for the new dataset and notebook?

It is the same; we wanted to use a new dataset since we already have a classify blog post from Jan that uses the enron emails dataset. I created a new notebook because I didn't want to overwrite the original notebook. Open to suggestions.

**Comment by drew** [comment]
> > This looks really similar to the existing `classify_freetext_with_nlp.ipynb` notebook. What's the motivation for the new dataset and notebook?
> 
> It is the same; we wanted to use a new dataset since we already have a classify blog post from Jan that uses the enron emails dataset. I created a new notebook because I didn't want to overwrite the original notebook. Open to suggestions.

I've always thought of blueprints being unique by use case. Maybe we can replace the existing notebook with the yelp dataset? I feel like having two of the same blueprints might be a bit confusing.

Alternatively, what if we use the CLI for the blog post? It'd be a good excuse to build out a one-liner for classifying data. It also doesn't require an artifact that's external to the blog post.

**Comment by yamini** [comment]
> > > This looks really similar to the existing `classify_freetext_with_nlp.ipynb` notebook. What's the motivation for the new dataset and notebook?
> > 
> > 
> > It is the same; we wanted to use a new dataset since we already have a classify blog post from Jan that uses the enron emails dataset. I created a new notebook because I didn't want to overwrite the original notebook. Open to suggestions.
> 
> I've always thought of blueprints being unique by use case. Maybe we can replace the existing notebook with the yelp dataset? I feel like having two of the same blueprints might be a bit confusing.
> 
> Alternatively, what if we use the CLI for the blog post? It'd be a good excuse to build out a one-liner for classifying data. It also doesn't require a source artifact that's external to the blog post.

If you're fine with my replacing the existing notebook, that might be the way to go? I like the suggestion of using the CLI, but the blog post is overdue so we might have to hold that for a future post.

**Review by drew — APPROVED** [review]

**Pull request merged**
