### PR TITLE
Update numerics_and_downstream_ml.ipynb

### PR DESCRIPTION
**Pull request by hhpang**
readability additions to downstream ML PyCaret notebook - instructions, cleaned up deprecated blueprint

### CODE REVIEW

**Comment by duggiemitchell** [comment]
@hhpang 👋🏾 are these changes required for Console release?

**Comment by yamini** [comment]
> @hhpang 👋🏾 are these changes required for Console release?

@duggiemitchell Yes, we do want it as part of the Console release, although we don't have to block on it.

**Review by andrewnc — APPROVED** [review]
LGTM

**Comment by hhpang** [comment]
thanks all

**Pull request merged**
